export const Tutorial = {
    // FOR GET
    GETTUTORIAL_REQUEST: "GETTUTORIAL_REQUEST",
    GETTUTORIAL_SUCCESS: "GETTUTORIAL_SUCCESS",
    GETTUTORIAL_FAILED: "GETTUTORIAL_FAILED",
    
    // FOR ADD
    ADDTUTORIAL_REQUEST: "ADDTUTORIAL_REQUEST",
    ADDTUTORIAL_SUCCESS: "ADDTUTORIAL_SUCCESS",
    ADDTUTORIAL_FAILED: "ADDTUTORIAL_FAILED",

    // FOR UPDATE
    UPDATETUTORIAL_REQUEST: "UPDATETUTORIAL_REQUEST",
    UPDATETUTORIAL_SUCCESS: "UPDATETUTORIAL_SUCCESS",
    UPDATETUTORIAL_FAILED: "UPDATETUTORIAL_FAILED",
    
    // FOR DELETE
    DELETETUTORIAL_REQUEST: "UPDATETUTORIAL_REQUEST",
    DELETETUTORIAL_SUCCESS: "UPDATETUTORIAL_SUCCESS",
    DELETETUTORIAL_FAILED: "UPDATETUTORIAL_FAILED"
}